/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardStats {
  'recentOrderCount' : bigint,
  'activeTaskCount' : bigint,
  'activeJobCount' : bigint,
}
export interface FoodOrder {
  'deliveryAddress' : string,
  'orderStatus' : string,
  'totalAmount' : number,
  'paymentMode' : string,
  'items' : Array<MenuItem>,
  'restaurant' : Restaurant,
}
export interface FoodOrderInput {
  'deliveryAddress' : string,
  'restaurantId' : bigint,
  'paymentMode' : string,
  'itemIds' : Array<bigint>,
}
export interface MenuItem {
  'name' : string,
  'description' : string,
  'price' : number,
}
export interface OrderHistoryEntry {
  'status' : string,
  'deliveryAddress' : string,
  'restaurantName' : string,
  'timestamp' : bigint,
  'paymentMode' : string,
  'items' : Array<MenuItem>,
  'totalPrice' : number,
}
export type OrderStatus = { 'preparing' : null } |
  { 'pending' : null } |
  { 'delivered' : null };
export interface Restaurant {
  'menu' : Array<MenuItem>,
  'name' : string,
  'cuisine' : string,
}
export interface Routine {
  'scheduledTime' : string,
  'name' : string,
  'isActive' : boolean,
}
export interface Task {
  'title' : string,
  'isCompleted' : boolean,
  'description' : string,
}
export type TaskStatus = { 'pending' : null } |
  { 'completed' : null };
export interface UserProfile { 'name' : string, 'aiAgentName' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addRoutine' : ActorMethod<[string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTask' : ActorMethod<[string, string], bigint>,
  'deleteRoutine' : ActorMethod<[bigint], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'getAIAgentName' : ActorMethod<[], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getOrderHistory' : ActorMethod<[], Array<OrderHistoryEntry>>,
  'getOrders' : ActorMethod<[], Array<FoodOrder>>,
  'getRestaurants' : ActorMethod<[], Array<Restaurant>>,
  'getRoutines' : ActorMethod<[], Array<Routine>>,
  'getTasks' : ActorMethod<[], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[FoodOrderInput], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleRoutine' : ActorMethod<[bigint, boolean], undefined>,
  'updateAIAgentName' : ActorMethod<[string], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateTaskStatus' : ActorMethod<[bigint, TaskStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];