/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'aiAgentName' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'recentOrderCount' : IDL.Nat,
  'activeTaskCount' : IDL.Nat,
  'activeJobCount' : IDL.Nat,
});
export const MenuItem = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Float64,
});
export const OrderHistoryEntry = IDL.Record({
  'status' : IDL.Text,
  'deliveryAddress' : IDL.Text,
  'restaurantName' : IDL.Text,
  'timestamp' : IDL.Int,
  'paymentMode' : IDL.Text,
  'items' : IDL.Vec(MenuItem),
  'totalPrice' : IDL.Float64,
});
export const Restaurant = IDL.Record({
  'menu' : IDL.Vec(MenuItem),
  'name' : IDL.Text,
  'cuisine' : IDL.Text,
});
export const FoodOrder = IDL.Record({
  'deliveryAddress' : IDL.Text,
  'orderStatus' : IDL.Text,
  'totalAmount' : IDL.Float64,
  'paymentMode' : IDL.Text,
  'items' : IDL.Vec(MenuItem),
  'restaurant' : Restaurant,
});
export const Routine = IDL.Record({
  'scheduledTime' : IDL.Text,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const Task = IDL.Record({
  'title' : IDL.Text,
  'isCompleted' : IDL.Bool,
  'description' : IDL.Text,
});
export const FoodOrderInput = IDL.Record({
  'deliveryAddress' : IDL.Text,
  'restaurantId' : IDL.Nat,
  'paymentMode' : IDL.Text,
  'itemIds' : IDL.Vec(IDL.Nat),
});
export const OrderStatus = IDL.Variant({
  'preparing' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
});
export const TaskStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addRoutine' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTask' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'deleteRoutine' : IDL.Func([IDL.Nat], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getAIAgentName' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getOrderHistory' : IDL.Func([], [IDL.Vec(OrderHistoryEntry)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(FoodOrder)], ['query']),
  'getRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
  'getRoutines' : IDL.Func([], [IDL.Vec(Routine)], ['query']),
  'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([FoodOrderInput], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleRoutine' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'updateAIAgentName' : IDL.Func([IDL.Text], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'updateTaskStatus' : IDL.Func([IDL.Nat, TaskStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'aiAgentName' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'recentOrderCount' : IDL.Nat,
    'activeTaskCount' : IDL.Nat,
    'activeJobCount' : IDL.Nat,
  });
  const MenuItem = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Float64,
  });
  const OrderHistoryEntry = IDL.Record({
    'status' : IDL.Text,
    'deliveryAddress' : IDL.Text,
    'restaurantName' : IDL.Text,
    'timestamp' : IDL.Int,
    'paymentMode' : IDL.Text,
    'items' : IDL.Vec(MenuItem),
    'totalPrice' : IDL.Float64,
  });
  const Restaurant = IDL.Record({
    'menu' : IDL.Vec(MenuItem),
    'name' : IDL.Text,
    'cuisine' : IDL.Text,
  });
  const FoodOrder = IDL.Record({
    'deliveryAddress' : IDL.Text,
    'orderStatus' : IDL.Text,
    'totalAmount' : IDL.Float64,
    'paymentMode' : IDL.Text,
    'items' : IDL.Vec(MenuItem),
    'restaurant' : Restaurant,
  });
  const Routine = IDL.Record({
    'scheduledTime' : IDL.Text,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const Task = IDL.Record({
    'title' : IDL.Text,
    'isCompleted' : IDL.Bool,
    'description' : IDL.Text,
  });
  const FoodOrderInput = IDL.Record({
    'deliveryAddress' : IDL.Text,
    'restaurantId' : IDL.Nat,
    'paymentMode' : IDL.Text,
    'itemIds' : IDL.Vec(IDL.Nat),
  });
  const OrderStatus = IDL.Variant({
    'preparing' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const TaskStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addRoutine' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTask' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'deleteRoutine' : IDL.Func([IDL.Nat], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getAIAgentName' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getOrderHistory' : IDL.Func([], [IDL.Vec(OrderHistoryEntry)], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(FoodOrder)], ['query']),
    'getRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
    'getRoutines' : IDL.Func([], [IDL.Vec(Routine)], ['query']),
    'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([FoodOrderInput], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleRoutine' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'updateAIAgentName' : IDL.Func([IDL.Text], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'updateTaskStatus' : IDL.Func([IDL.Nat, TaskStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };